#!/bin/bash


# Clean tree
git clean -dfx

# 64 bits
docker run --rm -ti -v "$(pwd):/pycares" quay.io/pypa/manylinux1_x86_64 /pycares/build-manylinux-wheels.sh

# 32 bits
docker run --rm -ti -v "$(pwd):/pycares" quay.io/pypa/manylinux1_i686 linux32 /pycares/build-manylinux-wheels.sh
