name: Release Wheels

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build_wheels:
    uses: ./.github/workflows/run-cibuildwheel.yml
    with:
      fail-fast: true

  build_sdist:
    uses: ./.github/workflows/run-sdist.yml

  upload_github:
    needs: [build_wheels, build_sdist]
    if: github.event_name == 'release' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true
      
      # This will simply modify the given github release
      # allowing for wheels to be uploaded to github's release
      # page automatically.
      - name: Upload Wheels To GitHub Release Page
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*

  upload_pypi:
    needs: [build_wheels, build_sdist]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true
      - run: ls -lR dist
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
