on:
  workflow_call:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          check-latest: true
          python-version: '3.13'
      - name: Install setuptools
        run: python -m pip install -U setuptools
      - name: Build sdist
        run: python setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
